# Generated by Django 6.1 on 2026-09-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_reel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
